
name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt-hotspot
        java-version: 17
        cache: gradle
    - name: Build
      run: bash ./gradlew assembleEmbedNoRecordRelease bundleEmbedNoRecordRelease
    - name: Artifact (Embed signed APK)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-embed.apk
        path: app/build/outputs/apk/embedNoRecord/release/app-embed-noRecord-release.apk
    - name: Artifact (Embed AAB w/o recording)
      uses: actions/upload-artifact@v3
      with:
        name: love-android-embed.aab
        path: app/build/outputs/bundle/embedNoRecordRelease/app-embed-noRecord-release.aab
    - name: Artifact (Debug symbols)
      uses: actions/upload-artifact@v3
      with:
        name: love-android-unstripped-debugsyms
        path: love/build/intermediates/library_jni
